language: android
jdk:
    - oraclejdk7
android:
    components:
        - tools
        - build-tools-23.0.1
        - platform-tools
        - android-23
script:
    bash gradlew test jacocoTestReport
after_success:
    - bash <(curl -s https://codecov.io/bash)